conf/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url('', include('blog.urls')),
]

src/mlb/blog/urls.py
from django.conf.urls import url

import mlb.blog.views


urlpatterns = [
    url(r'^$', mlb.blog.views.articles, name='articles'),
]

src/mlb/urls.py
from django.conf.urls import include, url

import mlb.blog.urls


urlpatterns = [
    url('', include(mlb.blog.urls, namespace='blog')),
]

src/project/blog/urls.py
from django.conf.urls import url

import project.blog.views


urlpatterns = [
    url(r'^$', project.blog.views.articles, name='articles'),
]

src/project/urls.py
from django.conf.urls import include, url

import project.blog.urls


urlpatterns = [
    url('', include(project.blog.urls, namespace='blog')),
]

src/project/blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=2000)
    slug = models.SlugField(max_length=2000, unique=True)
    summary = models.TextField(blank=True)
    body = models.TextField(blank=True)
    labels = models.ManyToManyField('Label')

    # Article publishing date/time - articles ordering is made by this field.
    # Also if it's blank - the article will be hidden.
    published_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'blog_article'

    def __str__(self):
        return self.title


class Label(models.Model):
    title = models.CharField(max_length=2000)
    slug = models.SlugField(max_length=2000, unique=True)

    class Meta:
        db_table = 'blog_label'

    def __str__(self):
        return self.title

src/project/blog/views.py
from django.views.generic.base import TemplateView


class ArticlesView(TemplateView):
    template_name = 'blog/articles.html'

articles = ArticlesView.as_view()

src/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Little Blog</title>
</head>
<body>
    <h1>My Little Blog</h1>
    <p>The name describes everything</p>
</body>
</html>

src/mlb/blog/templates/blog/articles.html
{% extends 'blog/base.html' %}

{% block page_content %}
  Articles list
{% endblock %}

src/project/blog/templates/blog/articles.html
{% extends 'core/base.html' %}

{% block page_content %}
  Articles list
{% endblock %}

src/project/core/templates/core/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load compress %}

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ project_metadata.title }}{% endblock %}</title>

    {% compress css %}
      <link rel="stylesheet" type="text/x-scss" href="{% static 'blog/base.scss' %}">
    {% endcompress %}

    {% block head %}
    {% endblock %}
  </head>
<body>
  <header class="page-header">
    <h1 class="title">
      <a href="{% url 'blog:articles' %}">
        {{ project_metadata.title }}
      </a>
    </h1>
  </header>

  <div class="page-container {% block page_class %}{% endblock %}">
    {% block page_content %}
    {% endblock %}
  </div>

  {% compress js %}
    <script type="module" src="{% static 'blog/base.js' %}"></script>
  {% endcompress %}

  {% block foot %}
  {% endblock %}
</body>
</html>